<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <xacro:include filename="$(find franka_description)/robots/tmr/inertia.xacro" />

  <xacro:macro name="argo_drive" params="name parent length:='0.04' radius:='0.05' offset_wheel_sign:='1' *origin">

    <xacro:property name="base_width" value="0.17" />
    <xacro:property name="base_depth" value="0.25" />
    <xacro:property name="base_height" value="0.077" />
    <xacro:property name="offset_wheel" value="0.085" />
    <xacro:property name="mass" value="0.5" />

    <link name="${name}_fixed_link" >
      <xacro:macro name="caster_base_geometry" params="xyz:='0 0 0'">
        <origin xyz="0 ${offset_wheel_sign*(base_depth/2 - offset_wheel)} ${base_height/2 - 0.004}" />
        <geometry>
          <box size="${base_width} ${base_depth} ${base_height}" />
        </geometry>
        <material name="darkgrey">
          <color rgba="0.3 0.3 0.3 1.0"/>
        </material>
      </xacro:macro>

      <visual>
        <xacro:caster_base_geometry/>
      </visual>

      <xacro:inertia-box mass="${mass}" width="${base_width}" height="${base_height}" depth="${base_depth}">
        <origin xyz="0 0 ${-base_height/2}" />
      </xacro:inertia-box>
    </link>

    <joint name="${name}_fixed_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child  link="${name}_fixed_link" />
    </joint>

    <link name="${name}_steering_link" />

    <joint name="${name}_steering_joint" type="continuous">
      <origin xyz="0 0 0"/>
      <parent link="${name}_fixed_link" />
      <child  link="${name}_steering_link" />
      <axis   xyz="0 0 1" />
      <limit  effort="500" velocity="20" />
      <dynamics damping="0.003" friction="0.0"/>
    </joint>

    <link name="${name}_link" >
      <xacro:macro name="argo_drive_geometry">
        <origin rpy="${pi/2} 0 0" />
        <geometry>
           <cylinder length="${length}" radius="${radius}" />
        </geometry>
        <material name="yellowish_brown">
          <color rgba="0.8 0.6 0.2 1.0"/>
        </material>
      </xacro:macro>

      <visual>
        <xacro:argo_drive_geometry/>
      </visual>
      <collision>
        <xacro:argo_drive_geometry/>
      </collision>

      <xacro:inertia-cylinder mass="${mass}" radius="${radius}" h="${length}" />

    </link>

    <joint name="${name}_joint" type="continuous">
      <origin xyz ="0 0 0" rpy="0 0 0" />
      <parent link="${name}_steering_link" />
      <child  link="${name}_link" />
      <axis   xyz="0 1 0" />
      <limit  effort="500" velocity="20" />
      <dynamics damping="0.003" friction="0.0"/>
    </joint>

  </xacro:macro>

</robot>