<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <xacro:include filename="$(find franka_description)/robots/tmr/inertia.xacro" />

  <xacro:macro name="caster_wheel" params="name mass parent length:='0.025' radius:='0.05' caster_joint_z:='-0.074' caster_steering_offset:='-0.035' *origin">

    <xacro:property name="base_width" value="0.04" />
    <xacro:property name="base_depth" value="0.03" />
    <xacro:property name="base_height" value="0.003" />

    <link name="${name}_fixed_link" >
      <xacro:macro name="caster_base_geometry" params="xyz:='0 0 0'">
        <origin xyz="0 0 ${-base_height/2}" />
        <geometry>
          <box size="${base_width} ${base_depth} ${base_height}" />
        </geometry>
        <material name="darkgrey">
          <color rgba="0.3 0.3 0.3 1.0"/>
        </material>
      </xacro:macro>

      <visual>
        <xacro:caster_base_geometry/>
      </visual>

      <xacro:inertia-box mass="${mass}" width="${base_width}" height="${base_height}" depth="${base_depth}">
        <origin xyz="0 0 ${-base_height/2}" />
      </xacro:inertia-box>
    </link>

    <joint name="${name}_steering_joint" type="continuous">
      <xacro:insert_block name="origin" />
      <parent link="${parent}" />
      <child  link="${name}_fixed_link" />
      <axis   xyz="0 0 1" />
      <limit  effort="500" velocity="20" />
      <dynamics damping="0.003" friction="0.0"/>
    </joint>

    <link name="${name}_link" >
      <xacro:macro name="caster_wheel_geometry">
        <origin rpy="${pi/2} 0 ${pi/2}" />
        <geometry>
           <mesh filename="package://franka_description/meshes/tmr/visual/caster.stl"/>
        </geometry>
        <material name="darkgrey">
          <color rgba="0.3 0.3 0.3 1.0"/>
        </material>
      </xacro:macro>

      <visual>
        <xacro:caster_wheel_geometry/>
      </visual>
      <collision>
        <xacro:caster_wheel_geometry/>
      </collision>

      <xacro:inertia-cylinder mass="${mass}" radius="${radius}" h="${length}" />

    </link>

    <joint name="${name}_joint" type="continuous">
      <origin xyz ="${caster_steering_offset} 0 ${caster_joint_z}" rpy="0 0 0" />
      <parent link="${name}_fixed_link" />
      <child  link="${name}_link" />
      <axis   xyz="0 1 0" />
      <limit  effort="500" velocity="20" />
      <dynamics damping="0.003" friction="0.0"/>
    </joint>

  </xacro:macro>

</robot>
