<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="tmr"
    params="mobile_robot_id
                  robot_ip:=''
                  ros2_control:=true
                  use_fake_hardware:=false
                  fake_sensor_commands:=false">

    <xacro:include filename="$(find franka_description)/robots/tmr/wheel.xacro" />
    <xacro:include filename="$(find franka_description)/robots/tmr/caster_wheel.xacro" />
    <xacro:include filename="$(find franka_description)/robots/tmr/bogie.xacro" />
    <xacro:include filename="$(find franka_description)/robots/tmr/inertia.xacro" />
    <xacro:include filename="$(find franka_description)/robots/tmr/lidar.xacro" />
    <xacro:include filename="$(find realsense2_description)/urdf/_d455.urdf.xacro" />
    <xacro:include filename="$(find olv_module_descriptions)/urdf/olv-imu01.urdf.xacro" />

    <xacro:property name="caster_radius" value="0.05" />
    <xacro:property name="caster_mass" value="0.5" />
    <xacro:property name="caster_joint_x" value="0.33" />
    <xacro:property name="caster_joint_y" value="0.26" />
    <xacro:property name="caster_vertical_offset" value="0.074" />
    <xacro:property name="caster_steering_offset" value="0.035" />
    <xacro:property name="caster_bogie_offset" value="0.01" />

    <xacro:property name="platform_height" value="0.3" />
    <xacro:property name="base_depth" value="0.575" />
    <xacro:property name="base_height" value="0.294" />
    <xacro:property name="base_width" value="0.80" />
    <xacro:property name="mass" value="75" />

    <xacro:property name="bogie_x" value="-0.18" />
    <xacro:property name="bogie_y" value="0.25" />
    <xacro:property name="bogie_z" value="0.075" />
    <xacro:property name="bogie_caster_x" value="-0.13" />

    <xacro:property name="wheel_radius" value="0.12" />
    <xacro:property name="wheel_width" value="0.08" />
    <xacro:property name="wheel_bogie_offset_y" value="0.015" />

    <xacro:property name="lidar_x" value="0.36057" />
    <xacro:property name="lidar_y" value="0.17943" />
    <xacro:property name="lidar_z" value="0.2215" />
    <xacro:property name="lidar_pitch" value="${pi}" />
    <xacro:property name="lidar_yaw" value="${pi*3/4}" />

    <!-- Main Platform Chassis -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi}" />
        <geometry>
          <mesh filename="package://franka_description/meshes/tmr/visual/tmr_base.dae" />
        </geometry>
        <material name="white">
          <color rgba="1.0 1.0 1.0 1.0" />
        </material>platform_height
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${pi}" />
        <geometry>
          <mesh filename="package://franka_description/meshes/tmr/collision/tmr_base_simplified.stl" />
        </geometry>
      </collision>
    </link>
platform_height
    <link name="base_inertia">
      <xacro:inertia-box mass="${mass}" width="${base_width}" height="${base_height}"
        depth="${base_depth}">
        <origin xyz="0 0 ${platform_height/2} " rpy="0 0 0" />
      </xacro:inertia-box>
    </link>

    <joint name="base_inertia_joint" type="fixed">
      <parent link="base_link" />
      <child link="base_inertia" />
    </joint>

    <!-- wheels and suspension -->
    <!-- front -->
    <xacro:caster_wheel name="caster_front_left" parent="base_link" mass="${caster_mass}"
      radius="${caster_radius}">
      <origin xyz="${caster_joint_x} ${caster_joint_y} ${caster_radius + caster_vertical_offset}" />
    </xacro:caster_wheel>

    <xacro:caster_wheel name="caster_front_right" parent="base_link" mass="${caster_mass}"
      radius="${caster_radius}">
      <origin xyz="${caster_joint_x} ${-caster_joint_y} ${caster_radius + caster_vertical_offset}" />
    </xacro:caster_wheel>

    <!-- rear left -->
    <xacro:bogie name="bogie_left" mass="3" parent="base_link">
      <origin xyz="${bogie_x} ${bogie_y} ${bogie_z}" />
    </xacro:bogie>

    <xacro:wheel lr="left" mass="1" parent="bogie_left_link" radius="${wheel_radius}"
      wheel_width="${wheel_width}">
      <origin xyz="${-bogie_x} ${wheel_bogie_offset_y} ${wheel_radius -bogie_z}" />
    </xacro:wheel>

    <xacro:caster_wheel name="caster_rear_left" mass="${caster_mass}" parent="bogie_left_link"
      radius="${caster_radius}">
      <origin
        xyz="${bogie_caster_x} ${caster_bogie_offset} ${caster_vertical_offset + caster_radius - bogie_z}" />
    </xacro:caster_wheel>

    <!-- rear right -->
    <xacro:bogie name="bogie_right" mass="3" parent="base_link">
      <origin xyz="${bogie_x} ${-bogie_y} ${bogie_z}" />
    </xacro:bogie>

    <xacro:wheel lr="right" mass="1" parent="bogie_right_link" radius="${wheel_radius}"
      wheel_width="${wheel_width}">
      <origin xyz="${-bogie_x} ${-wheel_bogie_offset_y} ${wheel_radius -bogie_z}" />
    </xacro:wheel>

    <xacro:caster_wheel name="caster_rear_right" parent="bogie_right_link" mass="${caster_mass}"
      radius="${caster_radius}">
      <origin
        xyz="${bogie_caster_x} ${-caster_bogie_offset} ${caster_vertical_offset + caster_radius - bogie_z}" />
    </xacro:caster_wheel>

    <!-- lidars -->
    <xacro:lidar name="lidar_front" parent="base_link">
      <origin xyz="${lidar_x} ${-lidar_y} ${lidar_z}" rpy="0 ${lidar_pitch} ${lidar_yaw}" />
    </xacro:lidar>
    <xacro:lidar name="lidar_rear" parent="base_link">
      <origin xyz="${-lidar_x} ${lidar_y} ${lidar_z}" rpy="0 ${lidar_pitch} ${lidar_yaw + pi}" />
    </xacro:lidar>

    <!-- cameras -->
    <xacro:sensor_d455 parent="base_link" name="camera_front_left">
      <origin xyz="0.36299 0.09833 0.1084" rpy="${-pi/2} ${-pi/18} ${-pi/6}" />
    </xacro:sensor_d455>
    <xacro:sensor_d455 parent="base_link" name="camera_front_right">
      <origin xyz="0.37749 -0.12345 0.108" rpy="${-pi/2} ${-pi/18} ${pi/6}" />
    </xacro:sensor_d455>
    <xacro:sensor_d455 parent="base_link" name="camera_rear_left">
      <origin xyz="-0.37749 0.12345 0.10840" rpy="${-pi/2} ${-pi/18} ${pi/6 + pi}" />
    </xacro:sensor_d455>
    <xacro:sensor_d455 parent="base_link" name="camera_rear_right">
      <origin xyz="-0.36299 -0.09833 0.1084" rpy="${-pi/2} ${-pi/18} ${-pi/6 + pi}" />
    </xacro:sensor_d455>

    <xacro:if value="${ros2_control}">
      <xacro:include filename="$(find franka_description)/robots/tmr/tmr.ros2_control.xacro" />
      <xacro:tmr_ros2_control
        mobile_robot_id="${mobile_robot_id}"
        robot_ip="${robot_ip}"
        use_fake_hardware="${use_fake_hardware}"
        fake_sensor_commands="${fake_sensor_commands}"
      />
    </xacro:if>

    <!-- IMU -->
    <link name="imu">
    </link>
    <joint name="base_to_imu" type="fixed">
      <parent link="base_link"/>
      <child link="imu"/>
      <origin xyz="-0.176 0.0545 0.15" rpy="0 ${-pi/2} 0"/>
    </joint>
    <xacro:olv-imu01 namespace="olv-imu01" parent_link="imu" mounting_side="bottom" mounting_rotation="0">
    </xacro:olv-imu01>
  </xacro:macro>
</robot>
